/*
 * This file was autogenerated by OSQP-Python on June 27, 2021 at 19:33:44.
 * 
 * This file contains the workspace variables needed by OSQP.
 */

#include "types.h"
#include "qdldl_interface.h"

// Define data structure
c_int Pdata_i[10] = {
0,
0,
1,
0,
1,
2,
0,
1,
2,
3,
};
c_int Pdata_p[5] = {
0,
1,
3,
6,
10,
};
c_float Pdata_x[10] = {
(c_float)1.00000000000000000000,
(c_float)0.23596294738754827747,
(c_float)1.00000000000000022204,
(c_float)-0.15380013141974249735,
(c_float)-0.08502345722119566962,
(c_float)1.00000000000000000000,
(c_float)0.01946011578874318887,
(c_float)0.22362028389487903501,
(c_float)0.24475386540905827437,
(c_float)1.00000000000000000000,
};
csc Pdata = {10, 4, 4, Pdata_p, Pdata_i, Pdata_x, -1};
c_int Adata_i[4] = {
0,
1,
2,
3,
};
c_int Adata_p[5] = {
0,
1,
2,
3,
4,
};
c_float Adata_x[4] = {
(c_float)0.99791917934532015089,
(c_float)0.99768635808680294907,
(c_float)0.99773503040679978326,
(c_float)0.99800002696157086302,
};
csc Adata = {4, 4, 4, Adata_p, Adata_i, Adata_x, -1};
c_float qdata[4] = {
(c_float)0.00000000000000000000,
(c_float)0.00000000000000000000,
(c_float)0.00000000000000000000,
(c_float)0.00000000000000000000,
};
c_float ldata[4] = {
(c_float)0.00000000000000000000,
(c_float)0.00000000000000000000,
(c_float)0.00000000000000000000,
(c_float)0.00000000000000000000,
};
c_float udata[4] = {
(c_float)2899119758018479962457859162112.00000000000000000000,
(c_float)3266244345765103439814124896256.00000000000000000000,
(c_float)3185827866621420943003028029440.00000000000000000000,
(c_float)2781553430925933427695569338368.00000000000000000000,
};
OSQPData data = {4, 4, &Pdata, &Adata, qdata, ldata, udata};

// Define settings structure
OSQPSettings settings = {(c_float)0.10000000000000000555, (c_float)0.00000100000000000000, 10, 1, 0, (c_float)5.00000000000000000000, 4000, (c_float)0.00100000000000000002, (c_float)0.00100000000000000002, (c_float)0.00010000000000000000, (c_float)0.00010000000000000000, (c_float)1.60000000000000008882, (enum linsys_solver_type) LINSYS_SOLVER, 0, 25, 1, };

// Define scaling structure
c_float Dscaling[4] = {
(c_float)0.34421454187438887962,
(c_float)0.30545368088592872446,
(c_float)0.31317920244853042488,
(c_float)0.35879232657031984166,
};
c_float Dinvscaling[4] = {
(c_float)2.90516488511668136141,
(c_float)3.27381879013416998703,
(c_float)3.19306005054516806041,
(c_float)2.78712761100259953650,
};
c_float Escaling[4] = {
(c_float)2.89911975801847976442,
(c_float)3.26624434576510358497,
(c_float)3.18582786662142103395,
(c_float)2.78155343092593332344,
};
c_float Einvscaling[4] = {
(c_float)0.34493228409560089398,
(c_float)0.30616203019120857842,
(c_float)0.31389015410317905319,
(c_float)0.35951133955644221096,
};
OSQPScaling scaling = {(c_float)1.00000000000000000000, Dscaling, Escaling, (c_float)1.00000000000000000000, Dinvscaling, Einvscaling};

// Define linsys_solver structure
c_int linsys_solver_L_i[10] = {
7,
4,
5,
6,
5,
6,
7,
6,
7,
7,
};
c_int linsys_solver_L_p[9] = {
0,
1,
2,
3,
4,
7,
9,
10,
10,
};
c_float linsys_solver_L_x[10] = {
(c_float)-0.09979191793453201509,
(c_float)-0.09976863580868029768,
(c_float)-0.09977350304067998665,
(c_float)-0.09980000269615708908,
(c_float)-0.07732647241440956942,
(c_float)0.20337643609238112430,
(c_float)0.21460174566316508882,
(c_float)0.23975469123233505986,
(c_float)-0.12402303682432111454,
(c_float)0.00400537190811003918,
};
csc linsys_solver_L = {10, 8, 8, linsys_solver_L_p, linsys_solver_L_i, linsys_solver_L_x, -1};
c_float linsys_solver_Dinv[8] = {
(c_float)-0.10000000000000000555,
(c_float)-0.10000000000000000555,
(c_float)-0.10000000000000000555,
(c_float)-0.10000000000000000555,
(c_float)0.90947222027490903784,
(c_float)0.91493488510009401971,
(c_float)1.00878079203560844235,
(c_float)0.96888006390747583030,
};
c_int linsys_solver_P[8] = {
4,
5,
6,
7,
1,
2,
3,
0,
};
c_float linsys_solver_bp[8];
c_float linsys_solver_sol[8];
c_float linsys_solver_rho_inv_vec[4] = {
(c_float)10.00000000000000000000,
(c_float)10.00000000000000000000,
(c_float)10.00000000000000000000,
(c_float)10.00000000000000000000,
};
c_int linsys_solver_Pdiag_idx[4] = {
0,
2,
5,
9,
};
c_int linsys_solver_KKT_i[18] = {
0,
1,
2,
3,
4,
1,
4,
5,
2,
4,
5,
6,
3,
7,
4,
5,
6,
0,
};
c_int linsys_solver_KKT_p[9] = {
0,
1,
2,
3,
4,
6,
9,
13,
18,
};
c_float linsys_solver_KKT_x[18] = {
(c_float)-10.00000000000000000000,
(c_float)-10.00000000000000000000,
(c_float)-10.00000000000000000000,
(c_float)-10.00000000000000000000,
(c_float)1.00000100000000013978,
(c_float)0.99768635808680294907,
(c_float)-0.08502345722119566962,
(c_float)1.00000099999999991773,
(c_float)0.99773503040679978326,
(c_float)0.22362028389487903501,
(c_float)0.24475386540905827437,
(c_float)1.00000099999999991773,
(c_float)0.99800002696157086302,
(c_float)1.00000099999999991773,
(c_float)0.23596294738754827747,
(c_float)-0.15380013141974249735,
(c_float)0.01946011578874318887,
(c_float)0.99791917934532015089,
};
csc linsys_solver_KKT = {18, 8, 8, linsys_solver_KKT_p, linsys_solver_KKT_i, linsys_solver_KKT_x, -1};
c_int linsys_solver_PtoKKT[10] = {
13,
14,
4,
15,
6,
7,
16,
9,
10,
11,
};
c_int linsys_solver_AtoKKT[4] = {
17,
5,
8,
12,
};
c_int linsys_solver_rhotoKKT[4] = {
0,
1,
2,
3,
};
QDLDL_float linsys_solver_D[8] = {
-10,
-10,
-10,
-10,
1,
1,
0,
1,
};
QDLDL_int linsys_solver_etree[8] = {
7,
4,
5,
6,
5,
6,
7,
-1,
};
QDLDL_int linsys_solver_Lnz[8] = {
1,
1,
1,
1,
3,
2,
1,
0,
};
QDLDL_int   linsys_solver_iwork[24];
QDLDL_bool  linsys_solver_bwork[8];
QDLDL_float linsys_solver_fwork[8];
qdldl_solver linsys_solver = {QDLDL_SOLVER, &solve_linsys_qdldl, &update_linsys_solver_matrices_qdldl, &update_linsys_solver_rho_vec_qdldl, &linsys_solver_L, linsys_solver_Dinv, linsys_solver_P, linsys_solver_bp, linsys_solver_sol, linsys_solver_rho_inv_vec, (c_float)0.00000100000000000000, 4, 4, linsys_solver_Pdiag_idx, 4, &linsys_solver_KKT, linsys_solver_PtoKKT, linsys_solver_AtoKKT, linsys_solver_rhotoKKT, linsys_solver_D, linsys_solver_etree, linsys_solver_Lnz, linsys_solver_iwork, linsys_solver_bwork, linsys_solver_fwork, };

// Define solution
c_float xsolution[4];
c_float ysolution[4];

OSQPSolution solution = {xsolution, ysolution};

// Define info
OSQPInfo info = {0, "Unsolved", OSQP_UNSOLVED, 0.0, 0.0, 0.0};

// Define workspace
c_float work_rho_vec[4] = {
(c_float)0.10000000000000000555,
(c_float)0.10000000000000000555,
(c_float)0.10000000000000000555,
(c_float)0.10000000000000000555,
};
c_float work_rho_inv_vec[4] = {
(c_float)10.00000000000000000000,
(c_float)10.00000000000000000000,
(c_float)10.00000000000000000000,
(c_float)10.00000000000000000000,
};
c_int work_constr_type[4] = {
0,
0,
0,
0,
};
c_float work_x[4];
c_float work_y[4];
c_float work_z[4];
c_float work_xz_tilde[8];
c_float work_x_prev[4];
c_float work_z_prev[4];
c_float work_Ax[4];
c_float work_Px[4];
c_float work_Aty[4];
c_float work_delta_y[4];
c_float work_Atdelta_y[4];
c_float work_delta_x[4];
c_float work_Pdelta_x[4];
c_float work_Adelta_x[4];
c_float work_D_temp[4];
c_float work_D_temp_A[4];
c_float work_E_temp[4];

OSQPWorkspace workspace = {
&data, (LinSysSolver *)&linsys_solver,
work_rho_vec, work_rho_inv_vec,
work_constr_type,
work_x, work_y, work_z, work_xz_tilde,
work_x_prev, work_z_prev,
work_Ax, work_Px, work_Aty,
work_delta_y, work_Atdelta_y,
work_delta_x, work_Pdelta_x, work_Adelta_x,
work_D_temp, work_D_temp_A, work_E_temp,
&settings, &scaling, &solution, &info};

